### PR TITLE
fix stream position bug

### PR DESCRIPTION
**Pull request by mikebranstein**
The myBlob stream is read multiple times in the function. The stream's position needs reset to the beginning before reading from it; otherwise, it will write 0 bytes to the "rejected" or "accepted" storage container.

### CODE REVIEW

**Comment by jeffprosise** [comment]
Thanks! I will look into it and fix.

**Comment by toddf1234** [comment]
Odd it worked fine for me.

Sent from my phone
On Mar 24, 2017, at 10:04 PM, Jeff Prosise <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks! I will look into it and fix.

**Comment by mikebranstein** [comment]
@toddf1234 odd indeed. 

Uploading to the rejected or approved blob container works, but the uploaded blob is 0 bytes. The `ToByteArrayAsync()` function reads the Stream to the end, so when `StoreBlobWithMetadata()` is called, the stream is already at it's last position, uploading 0 bytes.

**Comment by jeffprosise** [comment]
Fixed. I somehow edited out a line of code. It has been restored. Thanks!

**Pull request closed without merging**
